### ISSUE TITLE
Test suite fails on 32bit systems

### ISSUE THREAD

**Issue by eserte** [yanick/MsgPack-RPC#11]
See subject. More information:
http://analysis.cpantesters.org/solved?distv=MsgPack-RPC-2.0.1

Most fail reports also seem to have something like "i386" or "686" or "arm" in the archname column, see http://matrix.cpantesters.org/?dist=MsgPack-RPC%202.0.1;reports=1

**Comment by yanick** [comment]
I punted a new release that skips 64bits tests on 32bits archs. We'll see if it helps.

**Comment by yanick** [comment]
That seemed to have worked.
